apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
type: Opaque
stringData:
  PERSISTENCE_CONNECTION_STRING: "Server={{ .Values.persistence.host }};Port={{ .Values.persistence.port }};Database={{ .Values.persistence.database }};User id={{ .Values.persistence.user }};Password={{ .Values.persistence.password }};"