apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapi }}
  labels:
    component: {{ .Values.webapi }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: {{ .Values.webapi }}
