version: '3.7'

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=pomodoro
        ports:
            - "5432:5432"